services:

    mysql:
        image: mysql:9.6.0-oraclelinux9
        container_name: mysql
        restart: always
        networks: 
            - "mysql-network"
        ports:
            - "3306:3306"
        volumes:
            - ./secrets:/run/secrets:ro
            - mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
            - MYSQL_USER_FILE=/run/secrets/mysql_user
            - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
            - MYSQL_HOST_SERVER_FILE=/run/secrets/mysql_host_server
            - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        networks: 
            - "mysql-network"
        ports:
            - "8083:80"
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306

    js-app:
        image: 161.35.75.247:8084/js-app:1.0
        container_name: js-app
        user: "javauser"
        restart: unless-stopped
        networks:
            - "mysql-network"
        ports:
            - "8080:8080"
        volumes:
            - ./secrets:/run/secrets:ro
        depends_on:
            mysql:
                condition: service_healthy

volumes:
    mysql-data:
        name: mysql-data
        driver: local

networks:
    mysql-network:
        name: mysql-network
        driver: bridge
