#!/usr/bin/env groovy
//
// Jenkinsfile
//
// This project uses a limited shared library within the project scope only


def GIT_SHARED_LIB = "https://github.com/DevCTx/jenkins-limited-shared-library.git"
def GIT_PROJECT_URL = "https://github.com/DevCTx/DevOps.git"
def APP_DIR = "PART3 - Core/9. AWS Services/jma-ssh-dockerhub-ec2"


// This tells Jenkins to download a Shared Library from GitHub before running this pipeline
library identifier: "jenkins-limited-shared-library@main", 
    retriever: modernSCM([
        $class: "GitSCMSource", 
        remote: GIT_SHARED_LIB,
        credentialsId: "github-token"
    ])

pipeline {

	agent none

    options {
        skipDefaultCheckout(true)   // disable the automatic checkout
        preserveStashes(buildCount: 5)  // to activate the restart from stage with stashes preserved
    }
	
    parameters {        
        string( name: 'IMAGE_NAME', defaultValue: 'devct/demo-java-app', description: 'Image Name')
        string( name: 'VERSION', defaultValue: '3.0', description: 'App Version')
        string( name: 'HOST_PORT', defaultValue: '3080', description: 'Host Port')
        string( name: 'CONTAINER_PORT', defaultValue: '3080', description: 'Container Port')
        string( name: 'CONTAINER_NAME', defaultValue: 'java-app', description: 'Container Name')
    }

    environment {

        IMAGE_TAG = "${params.VERSION}.${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout SCM') {
            agent { label 'docker-agent' }

            steps {
                checkout([
                  $class: 'GitSCM',
                  branches: [[name: 'jenkins-jobs']],
                  userRemoteConfigs: [[url: GIT_PROJECT_URL ]],
                  extensions: [
                    [$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [
                      [$class: 'SparseCheckoutPath', path: "${APP_DIR}/"]
                    ]]
                  ]
                ])

                stash name: 'sources', includes: "${APP_DIR}/**"
            }
        }
        
        stage("build jar") {
            agent { label 'maven-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            
            steps {
                unstash 'sources'

                script {
                    dir("${APP_DIR}/") {
                        // build maven java app
                        buildJar()  // calls the Library function
                    }
                }

                stash name: 'app_files', includes: "${APP_DIR}/target/*.jar,${APP_DIR}/Dockerfile"
            }
        }

        stage("build and push image") {
            agent { label 'docker-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline

            steps {
                unstash 'app_files'

                script {
                    dir("${APP_DIR}/") {
                        // build and push docker image on docker hub
                        buildAndPushImage(params.IMAGE_NAME, env.IMAGE_TAG) // calls the Library function
                    }
                }
            }
        }

        stage("deploy") {
            agent { label 'aws-agent' }
        
            steps {
                script {
                    dir("${APP_DIR}/") {
                        // deploy docker image on AWS EC2 server via SSH
                        ec2DeployDockerCmdSSH(params.CONTAINER_NAME, params.HOST_PORT, params.CONTAINER_PORT, params.IMAGE_NAME, env.IMAGE_TAG)
                    }
                }
            }
        }
        
        stage("cleanup local and DockerHub Images") {
            agent { label 'docker-agent' }

            steps {
                script {
                    // clean docker image on Jenkins server
                    localCleanImageExceptTag(params.IMAGE_NAME, env.IMAGE_TAG)

                    // clean docker image on Docker Hub (because access to tag retention is not possible with a personal account)
                    dockerhubCleanImageExceptTag(params.IMAGE_NAME, env.IMAGE_TAG)
                }
            }
        }

        stage("cleanup EC2 Images") {
            agent { label 'aws-agent' }

            steps {
                script {
                    // clean docker image on AWS EC2 server
                    ec2CleanImageExceptTag(params.IMAGE_NAME, env.IMAGE_TAG)
                }
            }
        }
    }
} 
