#!/usr/bin/env groovy
//
// Jenkinsfile
//
// This project uses a limited shared library within the project scope only

def GIT_SHARED_LIB = "https://github.com/DevCTx/jenkins-limited-shared-library.git"
def GIT_PROJECT_URL = "https://github.com/DevCTx/DevOps.git"
def APP_DIR = "PART3 - Core/9. AWS Services/jma-ssh-dockerhub-ec2"


// This tells Jenkins to download a Shared Library from GitHub before running this pipeline
library identifier: "jenkins-limited-shared-library@main", 
    retriever: modernSCM([
        $class: "GitSCMSource", 
        remote: GIT_SHARED_LIB,
        credentialsId: "github-token"
    ])

pipeline {

	agent none

    options {
        skipDefaultCheckout(true)   // disable the automatic checkout
        preserveStashes(buildCount: 5)  // to activate the restart from stage with stashes preserved
    }
	
    parameters {        
        string( name: 'APP_IMAGE_NAME', defaultValue: 'demo-java-app', description: 'Image Name')
        string( name: 'APP_VERSION', defaultValue: '3.0', description: 'App Version')
        string( name: 'APP_HOST_PORT', defaultValue: '3080', description: 'Host Port')
        string( name: 'APP_CONTAINER_PORT', defaultValue: '3080', description: 'Container Port')
        string( name: 'APP_CONTAINER_NAME', defaultValue: 'java-app', description: 'Container Name')
    }

    stages {

        stage('Init env') {
            agent { label 'docker-agent' }

            steps {
                script {
                    env.APP_IMAGE_TAG = "${params.APP_VERSION}.${BUILD_NUMBER}"
                }
            }
        }

        stage('Checkout SCM') {
            agent { label 'docker-agent' }

            steps {
                checkout([
                  $class: 'GitSCM',
                  branches: [[name: 'jenkins-jobs']],
                  userRemoteConfigs: [[url: GIT_PROJECT_URL ]],
                  extensions: [
                    [$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[$class: 'SparseCheckoutPath', path: "${APP_DIR}/"]]]
                  ]
                ])

                stash name: 'sources', includes: "${APP_DIR}/**"
            }
        }
        
        stage("build jar") {
            agent { label 'maven-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            
            steps {
                unstash 'sources'

                script {
                    dir("${APP_DIR}/") {
                        // build maven java app
                        buildJar()  // calls the Library function
                    }
                }

                stash name: 'app_files', includes: "${APP_DIR}/target/*.jar,${APP_DIR}/Dockerfile"
            }
        }

        stage("build and push image") {
            agent { label 'docker-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline

            steps {
                unstash 'app_files'

                script {
                    dir("${APP_DIR}/") {
                        // build and push docker image on docker hub
                        dockerhubBuildAndPushImage(params.APP_IMAGE_NAME, env.APP_IMAGE_TAG) // calls the Library function
                    }
                }
            }
        }

        stage("deploy") {
            agent { label 'aws-agent' }
            steps {
                script {
                    dir("${APP_DIR}/") {
                        withCredentials([string(credentialsId: 'DOCKER_HUB_REPOSITORY', variable: 'DOCKER_HUB_REPOSITORY')]) {
                            ec2DeployDockerCmdSSH(
                                params.APP_CONTAINER_NAME,
                                params.APP_HOST_PORT,
                                params.APP_CONTAINER_PORT,
                                env.DOCKER_HUB_REPOSITORY,
                                params.APP_IMAGE_NAME,
                                env.APP_IMAGE_TAG
                            )
                        }
                    }
                }
            }
        }
        
        stage("cleanup EC2 Images") {
            agent { label 'aws-agent' }

            steps {
                script {
                    dir("${APP_DIR}/") {
                        // clean docker image on AWS EC2 server
                        ec2CleanImageExceptTag(params.APP_IMAGE_NAME, env.APP_IMAGE_TAG)
                    }
                }
            }
        }
        stage("cleanup local and DockerHub Images") {
            agent { label 'docker-agent' }

            steps {
                script {
                    dir("${APP_DIR}/") {
                        // clean docker image on Docker Hub (because access to tag retention is not possible with a personal account)
                        dockerhubCleanImageExceptTag(params.APP_IMAGE_NAME, env.APP_IMAGE_TAG)

                        // clean docker image on Jenkins server
                        localCleanImageExceptTag(params.APP_IMAGE_NAME, env.APP_IMAGE_TAG)
                    }
                }
            }
        }

    }
} 
