#!/usr/bin/env groovy

@Library('jenkins-shared-library') _ // underscore needed if no instruction before pipeline
def gv

def APP_DIR = "PART3 - Core/8. Jenkins CI-CD/java-dockerhub-shared"

pipeline {

	agent any

	tools {
		maven "maven-3.9.9"
	}

    parameters {
        string( name: 'VERSION', defaultValue: '2.0', description: 'App Version')
    }
	
    stages {
        stage("init") {
            steps {
                script {
                    gv = load "${APP_DIR}/script.groovy"
                }
            }
        }

        stage("test app") {
            steps {
                script {
                    dir("${APP_DIR}/") {
                        gv.testApp()  // calls the script function
                    }
                }
            }
        }

        stage("build jar") {
            when { expression { env.BRANCH_NAME == "main" } }
            steps {
                script {
                    dir("${APP_DIR}/") {
                        buildJar()  // calls the Library function
                    }
                }
            }
        }

        stage("build and push image") {
            when { expression { env.BRANCH_NAME == "main" } }
            steps {
                script {
                    dir("${APP_DIR}/") {
                        buildAndPushImage() // calls the Library function
                    }
                }
            }
        }
    }
}
