#!/usr/bin/env groovy

// This project used the global shared library

@Library('jenkins-shared-library') _ // underscore needed if no instruction before pipeline

def ROOT_DIR = "PART3 - Core/8. Jenkins CI-CD/Jenkins-exercises/jenkins-exercises"
def APP_DIR = "${ROOT_DIR}/app"

def CI_MSG = 'CI: version update'

pipeline {
    
    agent any

    tools {
        nodejs "nodejs-24.12.0"
    }

    environment {
        IMAGE = "devct/aws-nodejs-exercise"
    }

    stages {

        // stage('Check commit') {
        //     steps {
        //         scmSkip(deleteBuild: true, skipPattern: ".*${CI_MSG}.*")
        //     }
        // }

        // stage('Increment Version') {
        //     steps {
        //         script {
        //             dir("${APP_DIR}/") {
        //                 def version = IncrementNodejsPatchVersion()
        //                 env.VERSION = "$version-$BUILD_NUMBER"
        //                 echo "env.VERSION = ${env.VERSION}"
        //             }
        //         }
        //     }
        // }

        // stage("Run tests") {
        //     steps {
        //         script {
        //             dir("${APP_DIR}/") {
        //                 RunNodejsTests()
        //             }
        //         }
        //     }
        // }

        // stage("build and push image") {
        //     steps {
        //         script {
        //             dir("${ROOT_DIR}/") {
        //                 BuildAndPushDockerImage(
        //                     "docker-credentials", 
        //                     env.IMAGE,
        //                     env.VERSION
        //                 )
        //             }
        //         }
        //     }
        // }

        stage("deploy EC2 Web-Server") {
            steps {
                script {
                    dir("${ROOT_DIR}/") {
                        echo "Deploying ${env.IMAGE}:${env.VERSION} on EC2 ... "

                        env.VERSION = "1.2.10-11"
                            
                        withCredentials( [
                            string(credentialsId: 'DOCKER_USERNAME', variable: 'DOCKER_USERNAME'),
                            string(credentialsId: 'WEB_SERVER_PUBLIC_IP', variable: 'WEB_SERVER_PUBLIC_IP')
                        ]) {
                            sshagent(['EC2_WEB_SERVER_SSH_KEY']) {
                                sh """#!/bin/bash
                                    set -euo pipefail
                                    echo "Deploy ${DOCKER_USERNAME}/${env.IMAGE}:${env.VERSION} on EC2"

                                    ssh web-server "sudo mkdir -p /home/app && sudo chown ec2-user /home/app"
                                    scp docker-compose.yaml $WEB_SERVER_PUBLIC_IP:/home/app/

#                                    # On Jenkins, prepare a Bash with Env Vars :
#                                    ssh -o StrictHostKeyChecking=no ec2-user@$WEB_SERVER_PUBLIC_IP \
#                                        "CONTAINER_NAME=${env.IMAGE} \
#                                         IMAGE_NAME=${DOCKER_USERNAME}/${env.IMAGE} \
#                                         IMAGE_TAG=${env.VERSION}
#                                         HOST_PORT=3000 \
#                                         CONTAINER_PORT=3000 \
#                                         bash -s" << 'SCRIPT'
## On EC2 :
#set -euo pipefail
#echo "Deploying $IMAGE_NAME:$IMAGE_TAG"
#
#docker compose -f docker-compose.yaml up --detach                    
#
#echo "End of script"
#SCRIPT

                                """
                            }
                        }

                        BuildAndPushDockerImage(
                            "docker-credentials", 
                            env.IMAGE,
                            env.VERSION
                        )
                    }
                }
            }
        }

        // stage("commit version") {
        //     steps {
        //         script {
        //             dir("${ROOT_DIR}/") {
        //                 CommitVersionToGit("github-token", CI_MSG)
        //             }
        //         }
        //     }
        // }
    }
}
