#!/usr/bin/env groovy

// This project used the global shared library

@Library('jenkins-shared-library') _ // underscore needed if no instruction before pipeline

def ROOT_DIR = "PART3 - Core/9. AWS Services/AWS-exercises/aws-exercises"
def APP_DIR = "${ROOT_DIR}/app"

def CI_MSG = 'CI: version update'

pipeline {
    
    agent any

    tools {
        nodejs "nodejs-24.12.0"
    }

    environment {
        IMAGE = "devct/aws-nodejs-exercise"
    }

    stages {

        // stage('Check commit') {
        //     steps {
        //         scmSkip(deleteBuild: true, skipPattern: ".*${CI_MSG}.*")
        //     }
        // }

        // stage('Increment Version') {
        //     steps {
        //         script {
        //             dir("${APP_DIR}/") {
        //                 def version = IncrementNodejsPatchVersion()
        //                 env.VERSION = "$version-$BUILD_NUMBER"
        //                 echo "env.VERSION = ${env.VERSION}"
        //             }
        //         }
        //     }
        // }

        // stage("Run tests") {
        //     steps {
        //         script {
        //             dir("${APP_DIR}/") {
        //                 RunNodejsTests()
        //             }
        //         }
        //     }
        // }

        // stage("build and push image") {
        //     steps {
        //         script {
        //             dir("${ROOT_DIR}/") {
        //                 BuildAndPushDockerImage(
        //                     "docker-credentials", 
        //                     env.IMAGE,
        //                     env.VERSION
        //                 )
        //             }
        //         }
        //     }
        // }

        stage("deploy EC2 Web-Server") {
            steps {
                script {
                    dir("${ROOT_DIR}/") {
                        env.VERSION = "1.2.10-11"

                        echo "Deploying ${env.IMAGE}:${env.VERSION} on EC2 ... "
                            
                        withCredentials( [
                            string(credentialsId: 'WEB_SERVER_PUBLIC_IP', variable: 'WEB_SERVER_PUBLIC_IP')
                        ]) {
                            sshagent(['EC2_WEB_SERVER_SSH_KEY']) {
                                sh '''#!/bin/bash
                                    set -euo pipefail
                                    echo "Deploy ${IMAGE}:${VERSION} on EC2"

                                    ssh -o StrictHostKeyChecking=no ec2-user@$WEB_SERVER_PUBLIC_IP \\
                                        "sudo mkdir -p /home/app && sudo chown ec2-user /home/app"

                                    scp -o StrictHostKeyChecking=no ./docker-compose.yaml \\
                                        ec2-user@${WEB_SERVER_PUBLIC_IP}:/home/app/

                                    # On Jenkins, prepare a Bash with Env Vars :
                                    ssh -o StrictHostKeyChecking=no bash -s <<EOF
set -euo pipefail
cd /home/app

export CONTAINER_NAME=${IMAGE}
export IMAGE_NAME=${IMAGE}
export IMAGE_TAG=${VERSION}
export HOST_PORT=3000
export CONTAINER_PORT=3000

echo "Pulling and starting ${IMAGE}:${VERSION}..."
docker compose -f docker-compose.yaml up --detach
docker compose ps
EOF

                                    echo "Deploy completed"
                                '''                                
                            }
                        }
                    }
                }
            }
        }

        // stage("commit version") {
        //     steps {
        //         script {
        //             dir("${ROOT_DIR}/") {
        //                 CommitVersionToGit("github-token", CI_MSG)
        //             }
        //         }
        //     }
        // }
    }
}
