#!/usr/bin/env groovy
//
// Jenkinsfile
//
// This project uses a limited shared library within the project scope only

def GIT_SHARED_LIB = "https://github.com/DevCTx/jenkins-limited-shared-library.git"
def GIT_PROJECT_URL = "https://github.com/DevCTx/DevOps.git"
def APP_DIR = "PART3 - Core/9. AWS Services/jma-ssm-ecr-ec2"


// This tells Jenkins to download a Shared Library from GitHub before running this pipeline
library identifier: "jenkins-limited-shared-library@main", 
    retriever: modernSCM([
        $class: "GitSCMSource", 
        remote: GIT_SHARED_LIB,
        credentialsId: "github-token"
    ])

pipeline {

	agent none

    options {
        skipDefaultCheckout(true)       // disable the automatic checkout into each step
        preserveStashes(buildCount: 5)  // to activate the restart from stage with stashes preserved
    }

    environment {
        APP_IMAGE_NAME = 'devct/demo-java-app'
        APP_VERSION = '3.0'
        APP_HOST_PORT = '3080'
        APP_CONTAINER_PORT = '3080'
        APP_CONTAINER_NAME = 'java-app'
    }

    stages {

        stage('Init env') {
            agent { label 'docker-agent' }

            steps {
                script {
                    env.APP_IMAGE_TAG = "${env.APP_VERSION}.${env.BUILD_NUMBER}"
                }
            }
        }

        stage('Checkout SCM') {
            agent { label 'docker-agent' }

            steps {
                checkout([
                  $class: 'GitSCM',
                  branches: [[name: 'jenkins-jobs']],
                  userRemoteConfigs: [[url: GIT_PROJECT_URL ]],
                  extensions: [
                    [$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [
                      [$class: 'SparseCheckoutPath', path: "${APP_DIR}/"]
                    ]]
                  ]
                ])

                stash name: 'sources', includes: "${APP_DIR}/**"
            }
        }
        
        stage("build jar") {
            agent { label 'maven-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            
            steps {
                unstash 'sources'

                script {
                    dir("${APP_DIR}/") {
                        // build maven java app
                        buildJar()  // calls the Library function
                    }
                }

                stash name: 'app_files', includes: "${APP_DIR}/target/*.jar,${APP_DIR}/Dockerfile,${APP_DIR}/docker-compose.yaml"

            }
        }

        stage("build and push image") {
            agent { label 'docker-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline

            steps {
                unstash 'app_files'

                script {
                    dir("${APP_DIR}/") {
                        // build and push docker image on docker hub
                        buildAndPushImage(env.APP_IMAGE_NAME, env.APP_IMAGE_TAG) // calls the Library function
                    }
                }
            }
        }

        stage("deploy") {
            agent { label 'aws-agent' }
        
            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            steps {
                unstash 'app_files'

                script {
                    dir("${APP_DIR}/") {

                        // Write an environment file with the variables used into docker-compose.yaml
                        def envVars = [
                            IMAGE_NAME     : env.APP_IMAGE_NAME,
                            IMAGE_TAG      : env.APP_IMAGE_TAG,
                            HOST_PORT      : env.APP_HOST_PORT,
                            CONTAINER_PORT : env.APP_CONTAINER_PORT,
                            CONTAINER_NAME : env.APP_CONTAINER_NAME
                        ]

                        def writeEnvFile(path, vars) {
                            writeFile(
                                file: path,
                                text: vars.collect { key, value -> "${key}=${value}" }.join('\n') + '\n'
                            )
                        }

                        writeEnvFile('.env', envVars)

                        // Deploy by copying docker-compose.yaml + .env
                        ec2DeployEnvDockerComposeSSM()
                    }
                }
            }
        }
        
        stage("cleanup local and DockerHub Images") {
            agent { label 'docker-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            steps {
                script {
                    // clean docker image on Jenkins server
                    localCleanImageExceptTag(env.APP_IMAGE_NAME, env.APP_IMAGE_TAG)

                    // clean docker image on Docker Hub (because access to tag retention is not possible with a personal account)
                    dockerhubCleanImageExceptTag(env.APP_IMAGE_NAME, env.APP_IMAGE_TAG)
                }
            }
        }

        stage("cleanup EC2 Images") {
            agent { label 'aws-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            steps {
                script {
                    // clean docker image on AWS EC2 server avec SSM
                    ec2CleanImageExceptTagSSM(env.APP_IMAGE_NAME, env.APP_IMAGE_TAG)
                }
            }
        }
    }
} 
