#!/usr/bin/env groovy
//
// Jenkinsfile
//
// This project uses a limited shared library within the project scope only

def GIT_SHARED_LIB = "https://github.com/DevCTx/jenkins-limited-shared-library.git"
def GIT_PROJECT_URL = "https://github.com/DevCTx/DevOps.git"
def APP_DIR = "PART3 - Core/9. AWS Services/jma-ssm-ecr-ec2"


// This tells Jenkins to download a Shared Library from GitHub before running this pipeline
library identifier: "jenkins-limited-shared-library@main", 
    retriever: modernSCM([
        $class: "GitSCMSource", 
        remote: GIT_SHARED_LIB,
        credentialsId: "github-token"
    ])


// def writeEnvFile(path, vars) {
//     writeFile(
//         file: path,
//         text: vars.collect { key, value -> "${key}=${value}" }.join('\n') + '\n'
//     )
// }


pipeline {

	agent none

    options {
        skipDefaultCheckout(true)       // disable the automatic checkout into each step
        preserveStashes(buildCount: 5)  // to activate the restart from stage with stashes preserved
    }

    environment {
        APP_IMAGE_NAME = 'demo-java-app'
        APP_VERSION = '3.0'
        APP_HOST_PORT = '3080'
        APP_CONTAINER_PORT = '3080'
        APP_CONTAINER_NAME = 'java-app'
    }

    stages {

        stage('Init env') {
            agent { label 'docker-agent' }

            steps {
                script {
                    // Only at this step to be sure to get the build version
                    env.APP_IMAGE_TAG = "${env.APP_VERSION}.${env.BUILD_NUMBER}"
                }
            }
        }

        stage('Checkout SCM') {
            agent { label 'docker-agent' }

            steps {
                checkout([
                  $class: 'GitSCM',
                  branches: [[name: 'jenkins-jobs']],
                  userRemoteConfigs: [[url: GIT_PROJECT_URL ]],
                  extensions: [
                    [$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[$class: 'SparseCheckoutPath', path: "${APP_DIR}/"]]]
                  ]
                ])

                stash name: 'sources', includes: "${APP_DIR}/**"
            }
        }
        
        stage("build jar") {
            agent { label 'maven-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            
            steps {
                unstash 'sources'

                script {
                    dir("${APP_DIR}/") {
                        // build maven java app
                        buildJar()  // calls the Library function
                    }
                }

                stash name: 'app_files', includes: "${APP_DIR}/target/*.jar,${APP_DIR}/Dockerfile,${APP_DIR}/docker-compose.yaml"

            }
        }

        stage("build and push image") {
            agent { label 'docker-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline

            steps {
                unstash 'app_files'

                script {
                    dir("${APP_DIR}/") {
                        // build and push docker image on docker hub
                        ecrBuildAndPushImage() // calls the Library function
                    }
                }
            }
        }

        stage("deploy") {
            agent { label 'aws-agent' }
        
            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            steps {
                unstash 'app_files'

                script {
                    dir("${APP_DIR}/") {
                        // Deploy by copying docker-compose.yaml + .env
                        withCredentials([string(credentialsId: 'ECR_REPOSITORY', variable: 'ECR_REPOSITORY')]) {
                            ec2DeployEnvDockerComposeSSM()
                        }
                    }
                }
            }
        }
        
        stage("cleanup EC2 Images") {
            agent { label 'aws-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            steps {
                script {
                    // clean docker image on AWS EC2 instance server with SSM
                    ec2CleanImageExceptTagSSM()

                    // clean docker image on AWS ECR repository server with SSM
                    ecrCleanImageExceptTagSSM()
                }
            }
        }

        stage("cleanup local and DockerHub Images") {
            agent { label 'docker-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            steps {
                script {
                    // clean docker image on Jenkins server
                    withCredentials( [
                        string(credentialsId: 'ECR_REGISTRY', variable: 'ECR_REGISTRY')
                    ]) {
                        localCleanImageExceptTag(${ECR_REGISTRY})
                    }
                }
            }
        }

    }
} 
