#!/usr/bin/env groovy
//
// Jenkinsfile
//
// This project uses a limited shared library within the project scope only

// This tells Jenkins to download a Shared Library from GitHub before running this pipeline
library identifier: "jenkins-limited-shared-library@main", 
    retriever: modernSCM([
        $class: "GitSCMSource", 
        remote: "https://github.com/DevCTx/jenkins-limited-shared-library.git",
        credentialsId: "github-token"
    ])

def APP_DIR = "PART3 - Core/9. AWS Services/jma-ssm-ecr-ec2"

pipeline {

	agent none

    options {
        skipDefaultCheckout(true)   // disable the automatic checkout
    }

    environment {
        APP_IMAGE_NAME = 'devct/demo-java-app'
        APP_VERSION = '3.0'
        APP_HOST_PORT = '3080'
        APP_CONTAINER_PORT = '3080'
        APP_CONTAINER_NAME = 'java-app'
    }

    stages {

        stage('Init env') {
            agent { label 'maven-agent' }

            steps {
                script {
                    env.APP_IMAGE_TAG = "${env.APP_VERSION}.${env.BUILD_NUMBER}"
                }
            }
        }

        stage('Checkout SCM') {
            agent { label 'docker-agent' }

            steps {
                checkout scm
                stash name: 'sources', includes: "${APP_DIR}/**"
            }
        }
        
        stage("build jar") {
            agent { label 'maven-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            
            steps {
                script {
                    unstash 'sources'

                    dir("${APP_DIR}/") {
                        // build maven java app
                        buildJar()  // calls the Library function
                    }

                    stash name: 'app_files', includes: "${APP_DIR}/target/*.jar, ${APP_DIR}/Dockerfile"
                }
            }
        }

        stage("build and push image") {
            agent { label 'docker-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline

            steps {
                script {
                    unstash 'app_files'

                    dir("${APP_DIR}/") {
                        // build and push docker image on docker hub
                        buildAndPushImage(env.APP_IMAGE_NAME, env.APP_IMAGE_TAG) // calls the Library function
                    }
                }
            }
        }

        stage("deploy") {
            agent { label 'aws-agent' }
        
            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            steps {
                script {
                    dir("${APP_DIR}/") {
                        // Write an environment file with the variables used into docker-compose.yaml
                        writeFile file: '.env', text: """
IMAGE_NAME=${env.APP_IMAGE_NAME}
IMAGE_TAG=${env.APP_IMAGE_TAG}
HOST_PORT=${env.APP_HOST_PORT}
CONTAINER_PORT=${env.APP_CONTAINER_PORT}
CONTAINER_NAME=${env.APP_CONTAINER_NAME}
"""

                        // Deploy by copying docker-compose.yaml + .env
                        ec2DockerComposeDeployEnvSSM()
                    }
                }
            }
        }
        
        stage("cleanup local and DockerHub Images") {
            agent { label 'docker-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            steps {
                script {
                    // clean docker image on Jenkins server
                    localCleanImageExceptTag(env.APP_IMAGE_NAME, env.APP_IMAGE_TAG)

                    // clean docker image on Docker Hub (because access to tag retention is not possible with a personal account)
                    dockerhubCleanImageExceptTag(env.APP_IMAGE_NAME, env.APP_IMAGE_TAG)
                }
            }
        }

        stage("cleanup EC2 Images") {
            agent { label 'aws-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            steps {
                script {
                    // clean docker image on AWS EC2 server avec SSM
                    ec2CleanImageExceptTagSSM(env.APP_IMAGE_NAME, env.APP_IMAGE_TAG)
                }
            }
        }
    }
} 
