#!/usr/bin/env groovy
//
// Jenkinsfile
//
// This project uses a limited shared library within the project scope only

// This tells Jenkins to download a Shared Library from GitHub before running this pipeline
library identifier: "jenkins-limited-shared-library@main", 
    retriever: modernSCM([
        $class: "GitSCMSource", 
        remote: "https://github.com/DevCTx/jenkins-limited-shared-library.git",
        credentialsId: "github-token"
    ])

def APP_DIR = "PART3 - Core/9. AWS Services/jma-dockerhub-ec2"

pipeline {

	agent none

    options {
        skipDefaultCheckout(true)   // disable the automatic checkout
    }
	
    parameters {        
        string( name: 'IMAGE_NAME', defaultValue: 'devct/demo-java-app', description: 'Image Name')
        string( name: 'VERSION', defaultValue: '3.0', description: 'App Version')
        string( name: 'HOST_PORT', defaultValue: '3080', description: 'Host Port')
        string( name: 'CONTAINER_PORT', defaultValue: '3080', description: 'Container Port')
        string( name: 'CONTAINER_NAME', defaultValue: 'java-app', description: 'Container Name')
    }

    environment {
        IMAGE_TAG = "${params.VERSION}.${BUILD_NUMBER}"
    }

    stages {

        // define a custom checkout
        //    on the same branch that triggered the pipeline
        //    enabling submodules, and loading them recursively
        //    reusing the same GitHub credentials than parent
        // with the specified git and parent credentials
        //
        stage('Checkout SCM') {
            agent { label 'maven-agent' }

            steps {
                dir("${APP_DIR}/") {
                    checkout scm
                    sh "pwd"
                    sh "ls -R"
                }
                // stash name: 'source', includes: "${APP_DIR}/**"
            }
        }
        
        stage("build jar") {
            agent { label 'maven-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            
            steps {
                script {
                    deleteDir()
                    // unstash 'source'

                    dir("${APP_DIR}/") {
                        sh "pwd"
                        sh "ls -R"
                        sh "find . -name pom.xml"    
                        // build maven java app
                        buildJar()  // calls the Library function
                    }
                }
            }
        }    
    }
} 
