#!/usr/bin/env groovy
//
// Jenkinsfile
//
// This project uses a limited shared library within the project scope only

// This tells Jenkins to download a Shared Library from GitHub before running this pipeline
library identifier: "jenkins-limited-shared-library@main", 
    retriever: modernSCM([
        $class: "GitSCMSource", 
        remote: "https://github.com/DevCTx/jenkins-limited-shared-library.git",
        credentialsId: "github-token"
    ])

def APP_DIR = "PART3 - Core/9. AWS Services/jma-dockerhub-ec2"

pipeline {

	agent none

    options {
        skipDefaultCheckout(true)   // disable the automatic checkout
    }
	
    parameters {        
        string( name: 'IMAGE_NAME', defaultValue: 'devct/demo-java-app', description: 'Image Name')
        string( name: 'VERSION', defaultValue: '3.0', description: 'App Version')
        string( name: 'HOST_PORT', defaultValue: '3080', description: 'Host Port')
        string( name: 'CONTAINER_PORT', defaultValue: '3080', description: 'Container Port')
        string( name: 'CONTAINER_NAME', defaultValue: 'java-app', description: 'Container Name')
    }

    environment {
        IMAGE_TAG = "${params.VERSION}.${BUILD_NUMBER}"
    }

    stages {

        // define a custom checkout
        //    on the same branch that triggered the pipeline
        //    enabling submodules, and loading them recursively
        //    reusing the same GitHub credentials than parent
        // with the specified git and parent credentials
        //
        stage('Checkout SCM') {
            agent { label 'docker-agent' }

            steps {
/*
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: "*/${env.BRANCH_NAME}"]],
                    extensions: [[$class: 'SubmoduleOption',
                        parentCredentials: true,
                        recursiveSubmodules: true,
                        disableSubmodules: false
                    ]],
                    userRemoteConfigs: [[
                        url: 'https://github.com/DevCTx/DevOps.git',
                        credentialsId: 'github-token'
                    ]]
                ])
*/
                sh "pwd"
            }
        }
        
        stage("build jar") {
            agent { label 'maven-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            
            steps {
                script {
//                    dir("${APP_DIR}/") {
                    sh "pwd"
                    sh "ls -R"
                    sh "find . -name pom.xml"    
                    // build maven java app
                    // buildJar()  // calls the Library function
//                    }
                }
            }
        }

/*
        stage("build and push image") {
            agent { label 'docker-agent' }

            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline

            steps {
                script {
                    dir("${APP_DIR}/") {
                        // build and push docker image on docker hub
                        buildAndPushImage(params.IMAGE_NAME, env.IMAGE_TAG) // calls the Library function
                    }
                }
            }
        }

        stage("deploy") {
            agent { label 'aws-agent' }
        
            steps {
                script {
                    dir("${APP_DIR}/") {
                        // deploy docker image on AWS EC2 server
                        ec2Deploy(params.CONTAINER_NAME, params.HOST_PORT, params.CONTAINER_PORT, params.IMAGE_NAME, env.IMAGE_TAG)
                    }
                }
            }
        }
        
        stage("cleanup local and DockerHub Images") {
            agent { label 'docker-agent' }

            steps {
                script {
                    // clean docker image on Jenkins server
                    localCleanImageExceptTag(params.IMAGE_NAME, env.IMAGE_TAG)

                    // clean docker image on Docker Hub (because access to tag retention is not possible with a personal account)
                    dockerhubCleanImageExceptTag(params.IMAGE_NAME, env.IMAGE_TAG)
                }
            }
        }

        stage("cleanup EC2 Images") {
            agent { label 'aws-agent' }

            steps {
                script {
                    // clean docker image on AWS EC2 server
                    ec2CleanImageExceptTag(params.IMAGE_NAME, env.IMAGE_TAG)
                }
            }
        }
*/
    }
} 
