#!/usr/bin/env groovy

def APP_DIR = "PART3 - Core/8. Jenkins CI-CD/auto-versioning-pipeline"

pipeline {

	agent any

	tools {
		maven "maven-3.9.9"
	}

    environment {
        IMAGE = "devct/demo-java-app"
    }

    stages {
        stage('Increment Version') {
            steps {
                script {
                    dir("${APP_DIR}/") {
                        echo "Incrementing app version ..."

                        // Auto-increment patch
                        sh 'mvn build-helper:parse-version \
                        versions:set -DnextSnapshot=true \
                        versions:commit'

                        // Récupération fiable de la version effective
                        def version = sh(
                            script: "mvn help:evaluate -Dexpression=project.version -q -DforceStdout",
                            returnStdout: true
                        ).trim()

                        env.VERSION = "$version-$BUILD_NUMBER"
                        echo "env.VERSION = ${env.VERSION}"
                    }
                }
            }
        }

        stage("build jar") {
            when { expression { env.GIT_BRANCH == "origin/main" } }
            steps {
                script {
                    dir("${APP_DIR}/") {
                        echo "Building JAR file ..."
                        sh "mvn --no-transfer-progress clean package"
                    }
                }
            }
        }

        stage("build and push image") {
            when { expression { env.GIT_BRANCH == "origin/main" } }
            steps {
                script {
                    dir("${APP_DIR}/") {
                        echo "withCredentials"
                        withCredentials( [
                            usernamePassword( credentialsId: 'dockerhub-credentials',
                                            usernameVariable: 'DOCKER_USERNAME',
				                            passwordVariable: 'DOCKER_PASSWORD' )
                        ]) {
                            // Diagnoses 90% of jenkins+docker errors
                            echo "check docker env"
                            sh "whoami && id && docker --version && docker ps"

	                        echo "docker build image ..."
                            sh "docker build -t ${env.IMAGE}:${env.VERSION} ."
                            
	                        echo "docker login and push image ..."
                            sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                            sh "docker push ${env.IMAGE}:${env.VERSION}"
                        }
                    }
                }
            }
        }

        stage("update repo version") {
            when { expression { env.GIT_BRANCH == "origin/main" } }
            steps {
                script {
                    dir("${APP_DIR}/") {
                        echo "Update version into git repository ..."
                        withCredentials( [
                            usernamePassword( credentialsId: 'github-token',
                                              usernameVariable: 'USER',
					                          passwordVariable: 'PASS' )
                        ]) {
                            sh """
                                git config --global user.email 'jenkins@example.com'
                                git config --global user.name 'jenkins'
                                git remote set-url origin https://\${USER}:\${PASS}@github.com/DevCTx/DevOps.git
                                git add .
                                git status
                                git diff --cached --quiet || git commit -m 'CI: version Update'
                            git push origin HEAD:main
                            """
                        }
                    }
                }
            }
        }
    }
}

