#!/usr/bin/env groovy

// To simplify the understanding,
// this project is not using the global shared library

def APP_DIR = "PART3 - Core/8. Jenkins CI-CD/auto-versioning-pipeline"

pipeline {

	agent any

	tools {
		maven "maven-3.9.9"
	}

    environment {
        IMAGE = "devct/demo-java-app"
    }

    stages {
        stage('Increment Version') {
            steps {
                script {
                    dir("${APP_DIR}/") {
                        echo "Incrementing app version ..."

                        // Auto-increment patch
                        sh 'mvn build-helper:parse-version \
                        versions:set -DnewVersion=\\\${parsedVersion.majorVersion}.\\\${parsedVersion.minorVersion}.\\\${parsedVersion.nextIncrementalVersion} \
                        versions:commit'

                        def matcher = readFile('pom.xml') =~ '<version>(.+)</version>'
                        def version = matcher[0][1]
                        // Récupération fiable de la version effective
                        //def version = sh(
                        //    script: "mvn help:evaluate -Dexpression=project.version -q -DforceStdout",
                        //    returnStdout: true
                        //).trim()

                        env.VERSION = "$version-$BUILD_NUMBER"
                        echo "env.VERSION = ${env.VERSION}"
                    }
                }
            }
        }

        stage("build jar") {
            when { expression { env.GIT_BRANCH == "origin/main" } }
            steps {
                script {
                    dir("${APP_DIR}/") {
                        echo "Building JAR file ..."
                        sh "mvn --no-transfer-progress clean package"
                    }
                }
            }
        }

        stage("build and push image") {
            when { expression { env.GIT_BRANCH == "origin/main" } }
            steps {
                script {
                    dir("${APP_DIR}/") {
                        echo "withCredentials"
                        withCredentials( [
                            usernamePassword( credentialsId: 'dockerhub-credentials',
                                            usernameVariable: 'DOCKER_USERNAME',
				                            passwordVariable: 'DOCKER_PASSWORD' )
                        ]) {
                            // Diagnoses 90% of jenkins+docker errors
                            echo "check docker env"
                            sh "whoami && id && docker --version && docker ps"

	                        echo "docker build image ..."
                            sh "docker build -t ${env.IMAGE}:${env.VERSION} ."
                            
	                        echo "docker login and push image ..."
                            sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                            sh "docker push ${env.IMAGE}:${env.VERSION}"
                        }
                    }
                }
            }
        }
    }
}
