def gv

pipeline {

	agent any
	
	parameters {
		string(name: 'VERSION', defaultValue: '1.0', description: 'Application version')
		choice(name: 'ENVIRONMENT',
           choices: ['dev', 'test', 'prod'],
           description: 'Select environment')
		booleanParam(name: 'RUN_TESTS', defaultValue: true, description: 'Run tests?')
		text(name: 'MESSAGE',
         defaultValue: 'Deployment message',
         description: 'Write a message on several lines')
	}
	
	stages {
		stage('Init') {
			steps {
				script { gv = load "PART3 - Core/8. Jenkins CI-CD/java-maven-app/script.groovy" }
			}
		}
	
		stage('Build') {
			steps {
				script { gv.buildApp() }
			}
		}

		stage('Test') {
			steps {
				script { gv.testApp() }
			}
		}

		stage('Deploy') {
			steps {
				script { gv.deployApp()	}
			}
		}
	}
}
