def gv

pipeline {

	agent any
	
	parameters {
		string(name: 'VERSION', defaultValue: '1.0', description: 'Application version')
		booleanParam(name: 'RUN_TESTS', defaultValue: false, description: 'Run tests?')
	}
	
	stages {
		stage('Init') {
			steps {
				script { gv = load "PART3 - Core/8. Jenkins CI-CD/java-maven-app/script.groovy" }
			}
		}
	
		stage('Build') {
			steps {
				script { gv.buildApp() }
			}
		}

		stage('Test') {
			steps {
				script { gv.testApp() }
			}
		}

		stage('Deploy') {
            input {
                message "Select the deploy environment"
                ok "Done"
                parameters {
                    choice(name: 'ENVIRONMENT',
                       choices: ['dev', 'test', 'prod'],
                       description: 'Select environment')
                }
            }
			steps {
				script { 
                    gv.deployApp()	
                    echo "Deploying to ${ENVIRONMENT}"
                }
			}
		}
	}
}
