apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
  labels:
    app: mosquitto-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto-pod
  template:
    metadata:
      labels:
        app: mosquitto-pod
    spec:
      containers:
      - name: mosquitto-container
        image: eclipse-mosquitto:2.0
        ports:
        - containerPort: 1883
        volumeMounts:
        - name: configmap-volume
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        - name: secret-volume
          mountPath: /mosquitto/config/passwd
          subPath: passwd
          readOnly: true
      volumes:
      - name: configmap-volume
        configMap:
          name: mosquitto-configmap
      - name: secret-volume
        secret:
          secretName: mosquitto-secret
