#!/usr/bin/env groovy
//
// Jenkinsfile
//
// This project uses a limited shared library within the project scope only

// This tells Jenkins to download a Shared Library from GitHub before running this pipeline
library identifier: "jenkins-limited-shared-library@main", 
    retriever: modernSCM([
        $class: "GitSCMSource", 
        remote: "https://github.com/DevCTx/jenkins-limited-shared-library.git",
        credentialsId: "github-token"
    ])

def APP_DIR = "PART3 - Core/9. AWS Services/jma-ecr-ec2"

pipeline {

	agent any

    options {
        skipDefaultCheckout(true)   // disable the automatic checkout
    }
	
    tools {
		maven "maven-3.9.12"
	}

    environment {
        IMAGE_NAME = "devct/demo-java-app"
        VERSION = "3.0"
        HOST_PORT = "3080"
        CONTAINER_PORT = "3080"
        CONTAINER_NAME = "java-app"

        IMAGE_TAG = "${env.VERSION}.${BUILD_NUMBER}"
    }

    stages {

        // define a custom checkout
        //    on the same branch that triggered the pipeline
        //    enabling submodules, and loading them recursively
        //    reusing the same GitHub credentials than parent
        // with the specified git and parent credentials
        //
        stage('Checkout SCM') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: "*/${env.BRANCH_NAME}"]],
                    extensions: [[$class: 'SubmoduleOption',
                        parentCredentials: true,
                        recursiveSubmodules: true,
                        disableSubmodules: false
                    ]],
                    userRemoteConfigs: [[
                        url: 'https://github.com/DevCTx/DevOps.git',
                        credentialsId: 'github-token'
                    ]]
                ])
            }
        }
        
        stage("build jar") {
            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            steps {
                script {
                    dir("${APP_DIR}/") {
                        // build maven java app
                        buildJar()  // calls the Library function
                    }
                }
            }
        }

        stage("build and push image") {
            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            steps {
                script {
                    dir("${APP_DIR}/") {
                        // build and push docker image on docker hub
                        buildAndPushImage(env.IMAGE_NAME, env.IMAGE_TAG) // calls the Library function
                    }
                }
            }
        }

        stage("deploy") {
            steps {
                script {
                    dir("${APP_DIR}/") {
                        // deploy docker image on AWS EC2 server
                        // ec2Deploy(env.CONTAINER_NAME, env.HOST_PORT, env.CONTAINER_PORT, env.IMAGE_NAME, env.IMAGE_TAG)

                        // deploy the docker-compose.yaml and use docker compose to create the image on AWS EC2 server
                        // ec2DockerComposeDeploy(env.CONTAINER_NAME, env.HOST_PORT, env.CONTAINER_PORT, env.IMAGE_NAME, env.IMAGE_TAG)

                        // Write an environment file with the variables used into docker-compose.yaml
                        writeFile file: '.env', text: """
IMAGE_NAME=${env.IMAGE_NAME}
IMAGE_TAG=${env.IMAGE_TAG}
HOST_PORT=${env.HOST_PORT}
CONTAINER_PORT=${env.CONTAINER_PORT}
CONTAINER_NAME=${env.CONTAINER_NAME}
"""

                        // Deploy by copying docker-compose.yaml + .env
                        ec2DockerComposeDeployEnvSSM()
                    }
                }
            }
        }
        
        stage("cleanup") {
            steps {
                script {
                    // clean docker image on Jenkins server
                    localCleanImageExceptTag(env.IMAGE_NAME, env.IMAGE_TAG)

                    // clean docker image on AWS EC2 server
                    ec2CleanImageExceptTag(env.IMAGE_NAME, env.IMAGE_TAG)

                    // clean docker image on Docker Hub (because access to tag retention is not possible with a personal account)
                    dockerhubCleanImageExceptTag(env.IMAGE_NAME, env.IMAGE_TAG)
                }
            }
        }
    }
} 
