#!/usr/bin/env groovy

def ROOT_DIR = "PART3 - Core/8. Jenkins CI-CD/Jenkins-exercises/jenkins-exercises"
def APP_DIR = "${ROOT_DIR}/app"

pipeline {
    
    agent any

    tools {
        nodejs "nodejs-24.12.0"
    }

    environment {
        IMAGE = "devct/jenkins-nodejs-exercise"
    }

    stages {

        stage('Check commit') {
            steps {
                scmSkip(deleteBuild: true, skipPattern: '.*CI: version update.*')
            }
        }

        stage('Increment Version') {
            steps {
                script {
                    dir("${APP_DIR}/") {
                        echo "Incrementing app version ..."
                        def version = sh(
                            script: "npm version patch --no-git-tag-version", 
                            returnStdout: true
                        ).trim()
                        version = version.replace("v", "")
                        env.VERSION = "$version-$BUILD_NUMBER"
                        echo "env.VERSION = ${env.VERSION}"
                    }
                }
            }
        }

        stage("Run tests") {
            steps {
                script {
                    dir("${APP_DIR}/") {
                        echo "Building NodeJS App ..."
                        sh "npm install"
                        sh "npm run test"
                    }
                }
            }
        }

        stage("build and push image") {
            steps {
                script {
                    dir("${ROOT_DIR}/") {
                        withCredentials([
                            usernamePassword(credentialsId: 'docker-credentials',
                                            usernameVariable: 'USER',
                                            passwordVariable: 'PSWD')
                        ]) {
                            echo "check docker env"
                            sh "whoami && id && docker --version && docker ps"
                            
                            echo "Remove all existing images of ${env.IMAGE}..."
                            sh "docker images ${env.IMAGE} -q | xargs -r docker rmi -f"

                            echo "Build new image ${env.IMAGE}:${env.VERSION}..."
                            sh "docker build -t ${env.IMAGE}:${env.VERSION} . "

                            echo "Login and Push image to Docker Hub..."
                            sh 'echo $PSWD | docker login -u $USER --password-stdin'
                            sh "docker push ${env.IMAGE}:${env.VERSION}"
                        }
                    }
                }
            }
        }

        stage("commit version") {
            steps {
                script {
                    dir("${ROOT_DIR}/") {
                        echo "Update version into git repository ..."
                        withCredentials([
                            usernamePassword(credentialsId: 'github-token',
                                            usernameVariable: 'USER',
                                            passwordVariable: 'PASS')
                        ]) {
                            sh """
                                git config user.email 'jenkins@example.com'
                                git config user.name 'jenkins'
                                git remote set-url origin https://\${USER}:\${PASS}@github.com/DevCTx/DevOps.git
                                git add .
                                git status
                                git diff --cached --quiet || git commit -m 'CI: version update'
                                git push origin HEAD:main
                            """
                        }
                    }
                }
            }
        }
    }
}
