services:

    java-maven-app:
        container_name: ${CONTAINER}
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        restart: unless-stopped
        ports:
            - "${HOST_PORT}:${CONTAINER_PORT}"

    postgres:
        container_name: postgres
        image: postgres:15
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=my-pwd

        
