services:

    java-maven-app:
        container_name: java-app
        image: devct/demo-java-app:3.0
        restart: unless-stopped
        ports:
            - "8080:8080"

    postgres:
        container_name: postgres
        image: postgres:15
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=my-pwd

        
