#!/usr/bin.env groovy

def APP_DIR = "PART3 - Core/9. AWS Services/java-maven-app"

pipeline {   
    agent any
    stages {
        stage("test") {
            steps {
                script {
                    echo "Testing the application..."

                }
            }
        }
        stage("build") {
            steps {
                script {
                    echo "Building the application..."
                }
            }
        }

        stage("deploy") {
            steps {
                script {
                    dir("${APP_DIR}/") {
                        echo "Deploying the application..."
                        def dockerCmd = 'docker run -d -p 3080:3080 devct/demo-java-app:2.0'
                        sshagent(['ec2-server-key']) {
                            sh "ssh -o StrictHostKeyChecking=no ec2-user@13.38.130.100 ${dockerCmd}"
                        }
                    }
                }
            }
        }               
    }
} 
