#!/usr/bin/env groovy

//
// This project uses a limited shared library within the project scope only

library identifier: "jenkins-limited-shared-library@main", 
    retriever: modernSCM([
        $class: "GitSCMSource", 
        remote: "https://github.com/DevCTx/jenkins-limited-shared-library.git",
        credentialsId: "github-token"
    ])

def APP_DIR = "PART3 - Core/9. AWS Services/java-maven-app"

pipeline {

	agent any

	tools {
		maven "maven-3.9.12"
	}

    parameters {        
        string( name: 'IMAGE_NAME', defaultValue: 'devct/demo-java-app', description: 'Image Name')
        string( name: 'VERSION', defaultValue: '3.0', description: 'App Version')
        string( name: 'HOST_PORT', defaultValue: '3080', description: 'Host Port')
        string( name: 'CONT_PORT', defaultValue: '3080', description: 'Container Port')
    }

	environment {
	    EC2_HOST = credentials('EC2_HOST')
	    EC2_USER = credentials('EC2_USER')
	}
		
    stages {

        stage("build jar") {
            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            steps {
                script {
                    dir("${APP_DIR}/") {
                        buildJar()  // calls the Library function
                    }
                }
            }
        }

        stage("build and push image") {
            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            steps {
                script {
                    dir("${APP_DIR}/") {
                        buildAndPushImage() // calls the Library function
                    }
                }
            }
        }

        stage("deploy") {
            steps {
                script {
                    dir("${APP_DIR}/") {
                        echo "Deploying the application..."

                        // Construire la commande docker comme un string unique
                        def dockerRunCmd = "docker pull ${params.IMAGE_NAME}:${params.VERSION} && " +
                                           "docker stop java-app || true && " +
                                           "docker rm java-app || true && " +
                                           "docker run -d --name java-app -p ${params.HOST_PORT}:${params.CONT_PORT} ${params.IMAGE_NAME}:${params.VERSION}"

                        sshagent(['ec2-server-key']) {
                            sh "ssh -o StrictHostKeyChecking=no ${env.EC2_USER}@${env.EC2_HOST} '${dockerRunCmd}'"
                        }
                    }
                }
            }
        }              
    }
} 
