#!/usr/bin/env groovy
//
// This project uses a limited shared library within the project scope only

library identifier: "jenkins-limited-shared-library@main", 
    retriever: modernSCM([
        $class: "GitSCMSource", 
        remote: "https://github.com/DevCTx/jenkins-limited-shared-library.git"
    ])

def APP_DIR = "PART3 - Core/9. AWS Services/java-maven-app"

pipeline {

	agent any

	tools {
		maven "maven-3.9.12"
	}

    parameters {        
        string( name: 'IMAGE_NAME', defaultValue: 'devct/demo-java-app', description: 'Image Name')
        string( name: 'VERSION', defaultValue: '3.0', description: 'App Version')
        string( name: 'HOST_PORT', defaultValue: '3080', description: 'Host Port')
        string( name: 'CONTAINER_PORT', defaultValue: '3080', description: 'Container Port')
        string( name: 'CONTAINER_NAME', defaultValue: 'java-app', description: 'Container Name')
    }

    environment {
        IMAGE_TAG = "${params.VERSION}.${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout SCM') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    doGenerateSubmoduleConfigurations: false, // ⚠️ important
                    userRemoteConfigs: [[url: 'https://github.com/DevCTx/DevOps.git']]
                ])
            }
        }
        
        stage("build jar") {
            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            steps {
                script {
                    dir("${APP_DIR}/") {
                        // build maven java app
                        buildJar()  // calls the Library function
                    }
                }
            }
        }

        stage("build and push image") {
            when { expression { env.BRANCH_NAME == "jenkins-jobs" } }  //env.GIT_NAME == "origin/jenkins-jobs" in single pipeline
            steps {
                script {
                    dir("${APP_DIR}/") {
                        // build and push docker image on docker hub
                        buildAndPushImage(params.IMAGE_NAME, env.IMAGE_TAG) // calls the Library function
                    }
                }
            }
        }

        stage("deploy") {
            steps {
                script {
                    dir("${APP_DIR}/") {
                        // deploy docker image on AWS EC2 server
                        ec2Deploy(params.CONTAINER_NAME, params.HOST_PORT, params.CONTAINER_PORT, params.IMAGE_NAME, env.IMAGE_TAG)
                    }
                }
            }
        }
        
        stage("cleanup") {
            steps {
                script {
                    // clean docker image on Jenkins server
                    localCleanImageExceptTag(params.IMAGE_NAME, env.IMAGE_TAG)

                    // clean docker image on AWS EC2 server
                    ec2CleanImageExceptTag(params.IMAGE_NAME, env.IMAGE_TAG)
                }
            }
        }
    }
} 
